# Generated by Django 4.1.4 on 2022-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_viewer_alter_movie_owner_alter_relation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True),
        ),
    ]
