# Generated by Django 4.1.4 on 2022-12-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='like',
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.CharField(blank=True, choices=[('👍', 'like'), ('👎', 'Unlike')], max_length=20, null=True),
        ),
    ]
